name: Main

on:
  push:
    branches: [main]

defaults:
  run:
    working-directory: static

jobs:
  build-and-deploy:
    runs-on: ubuntu-20.04

    steps:
      - name: checkout code
        uses: actions/checkout@v3
      - name: set up node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: install dependencies
        run: npm ci
      - name: run tests
        run: npm run lint
      - name: build code
        run: npm run build:prod
